# Generated by Django 5.2.10 on 2026-02-13 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(choices=[('Admin', 'Admin'), ('User', 'User'), ('Finance', 'Finance'), ('Finance Manager', 'Finance Manager'), ('Department Manager', 'Department Manager'), ('Director', 'Director'), ('Managing Director', 'Managing Director'), ('Staff', 'Staff'), ('Head of Department', 'Head of Department'), ('Financial Controller', 'Financial Controller'), ('Director General', 'Director General')], max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('can_define_users', models.BooleanField(default=False)),
                ('can_delegate', models.BooleanField(default=False)),
                ('can_create_imprest', models.BooleanField(default=False)),
                ('can_surrender_own', models.BooleanField(default=False)),
                ('can_create_department_imprest', models.BooleanField(default=False)),
                ('can_create_payment_transfers', models.BooleanField(default=False)),
                ('can_approve_payment_transfers', models.BooleanField(default=False)),
                ('can_approve_documents', models.BooleanField(default=False)),
                ('can_enter_surrenders', models.BooleanField(default=False)),
                ('can_update_surrenders', models.BooleanField(default=False)),
                ('can_approve_surrenders', models.BooleanField(default=False)),
                ('can_access_all_documents', models.BooleanField(default=False)),
                ('can_access_department_documents', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': '_cplimpRoles',
            },
        ),
        migrations.CreateModel(
            name='UserManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('user_email', models.EmailField(max_length=254, unique=True)),
                ('user_password', models.CharField(max_length=255)),
                ('individual_site', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('department_role', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Suspended', 'Suspended')], default='Active', max_length=20)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='users.role')),
            ],
            options={
                'db_table': '_cplimpUserManagement',
            },
        ),
        migrations.CreateModel(
            name='UserDelegation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Active', 'Active'), ('Expired', 'Expired'), ('Cancelled', 'Cancelled')], default='Scheduled', max_length=20)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('remarks', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delegate_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations_received', to='users.usermanagement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations_made', to='users.usermanagement')),
            ],
            options={
                'db_table': '_cplimpUserDelegation',
            },
        ),
        migrations.AddIndex(
            model_name='usermanagement',
            index=models.Index(fields=['user_email'], name='DcplimpUser_user_em_54008e_idx'),
        ),
        migrations.AddIndex(
            model_name='usermanagement',
            index=models.Index(fields=['status'], name='DcplimpUser_status_5245cb_idx'),
        ),
        migrations.AddIndex(
            model_name='userdelegation',
            index=models.Index(fields=['from_date', 'to_date'], name='DcplimpUser_from_da_bbdab0_idx'),
        ),
        migrations.AddIndex(
            model_name='userdelegation',
            index=models.Index(fields=['status'], name='DcplimpUser_status_ad47ef_idx'),
        ),
    ]
