# Generated by Django 5.2.10 on 2026-03-02 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdelegation',
            name='user',
        ),
        migrations.AddField(
            model_name='userdelegation',
            name='user_name',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
