# Generated by Django 5.2.10 on 2026-03-02 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_userdelegation_user_userdelegation_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdelegation',
            name='user_email',
            field=models.EmailField(default=22, max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
