# Generated by Django 5.2.10 on 2026-04-04 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userdelegation_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermanagement',
            old_name='individual_site',
            new_name='individual_role',
        ),
    ]
