# Generated by Django 5.2.10 on 2026-02-13 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImprestApproval',
            fields=[
                ('approval_id', models.AutoField(primary_key=True, serialize=False)),
                ('imprest', models.IntegerField()),
                ('approver_role', models.CharField(choices=[('HOD', 'HOD'), ('FC', 'FC'), ('DG', 'DG')], max_length=5)),
                ('approver', models.IntegerField()),
                ('decision', models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected')], max_length=10)),
                ('comments', models.TextField(blank=True, null=True)),
                ('decision_datetime', models.DateTimeField()),
                ('created_by', models.IntegerField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.IntegerField(blank=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'imprest_approvals',
                'ordering': ['-decision_datetime'],
            },
        ),
        migrations.CreateModel(
            name='ImprestAttachment',
            fields=[
                ('attachment_id', models.AutoField(primary_key=True, serialize=False)),
                ('imprest', models.IntegerField()),
                ('file_path', models.FileField(upload_to='imprest/attachments/')),
                ('attachment_type', models.CharField(choices=[('Support', 'Support'), ('Receipt', 'Receipt')], max_length=10)),
                ('uploaded_by', models.IntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.IntegerField(blank=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'imprest_attachments',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ImprestRequest',
            fields=[
                ('imprest_id', models.AutoField(primary_key=True, serialize=False)),
                ('request_no', models.CharField(blank=True, max_length=50, unique=True)),
                ('user_requested', models.IntegerField()),
                ('user_entered', models.IntegerField()),
                ('user_surrendered', models.IntegerField(blank=True, null=True)),
                ('surrender_datetime', models.DateTimeField(blank=True, null=True)),
                ('close_datetime', models.DateTimeField(blank=True, null=True)),
                ('department', models.IntegerField()),
                ('project', models.IntegerField()),
                ('purpose', models.TextField()),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Pending_HOD', 'Pending HOD'), ('Pending_FC', 'Pending FC'), ('Pending_DG', 'Pending DG'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Surrendered', 'Surrendered'), ('Closed', 'Closed')], default='Draft', max_length=20)),
                ('created_by', models.IntegerField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.IntegerField(blank=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'imprest_requests',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='ImprestRequestLine',
            fields=[
                ('breakdown_id', models.AutoField(primary_key=True, serialize=False)),
                ('imprest', models.IntegerField()),
                ('expense_head', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('gl_account', models.CharField(blank=True, max_length=50, null=True)),
                ('account_name', models.CharField(blank=True, max_length=200, null=True)),
                ('estimated_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('spent_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('supplier_no', models.CharField(blank=True, max_length=50, null=True)),
                ('created_by', models.IntegerField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.IntegerField(blank=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'imprest_request_lines',
                'ordering': ['breakdown_id'],
            },
        ),
    ]
