# Generated by Django 5.2.10 on 2026-03-04 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imprest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imprestrequestline',
            name='debtor_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='imprestrequestline',
            name='debtor_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
