# Generated by Django 5.2.10 on 2026-03-05 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imprest', '0002_imprestrequestline_debtor_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imprestrequestline',
            name='surrendered_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
