# Generated by Django 5.2.10 on 2026-03-16 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imprest', '0003_imprestrequestline_surrendered_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imprestrequest',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Pending_HOD', 'Submitted'), ('Pending_FC', 'Pending FC'), ('Pending_DG', 'Pending DG'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Surrendered', 'Surrendered'), ('Closed', 'Closed'), ('Cancelled', 'Cancelled')], default='Draft', max_length=20),
        ),
    ]
