# Generated by Django 5.2.10 on 2026-03-16 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imprest', '0004_alter_imprestrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imprestrequest',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('HODApproved', 'HOD Approved'), ('HODRejected', 'HOD Rejected'), ('FinanceApproved', 'Finance Approved'), ('FinanceRejected', 'Finance Rejected'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Surrendered', 'Surrendered')], default='Draft', max_length=20),
        ),
    ]
